"""Remove local followers, add github token

Revision ID: 2ff2cc6e36da
Revises: e9f5c0db44e6
Create Date: 2026-08-25 13:51:46.582613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2ff2cc6e36da'
down_revision: Union[str, None] = 'e9f5c0db44e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('github_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'github_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_url', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'github_access_token')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
